<?
include('inc/config.php');


if($_SERVER['REQUEST_METHOD'] == 'POST'){
	
	
	
	$name = $_POST['name'];
	$email = $_POST['email'];
	$file_title = $_POST['file_title'];
	$file_description = $_POST['file_description'];

	
	
	
	
$post_name = array_keys($_POST);

$txt = 'A customer visiting Vertice Services website sent you a document in attach and these are informations about this file.<br><br>';

foreach ($post_name as $name){
	$txt .= "<b>$name </b>". ": " . $_POST[$name] . "<br>";
	
}

$send_files = '';

$files = $_FILES['file'];

	 	for($x = 0 ; $x < count($files);$x++){
	 		
	 		if($files['name'][$x]){
	 			$files_send++;
	 			
	 			$name_file = md5(time() . $files['name'][$x]) . extencao($files['name'][$x]);
	 			
	 			
	 			$caminho = "img_temp/" . $name_file;
	 			if(img_permitidas($name_file)){
	 				
	 				if(move_uploaded_file($files['tmp_name'][$x],$caminho)){
	 					
	 					$file_send_server++;
	 					
	 					$send_files[] = $caminho;
	 					
	 					/// o tamanho maximo permitodo para a imagem
	 					
	 					
	 					
	 				
	 					
	 				}else{
	 					$file_send_user_error++;
	 					
	 				}
	 				
	 				
	 			}
	 			
	 			
	 		}
	 		
	 		
	 	}
	 	
	 	
	 	
	 	/// envia os emails
	 	
	 	sendmail($_POST['name'],$email,'Vertice Services','info@verticeservices.com','Available document in attach','',$txt,$send_files);
	 	//sendmail($_POST['name'],$email,'Vertice Services','dev@wespadigital.com','Available document in attach','',$txt,$send_files);
	 	
	 	$send = true;
	
	
	
}


?>

<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
   <meta name="GENERATOR" content="Mozilla/4.79 [en] (WinNT; U) [Netscape]">
   <meta name="Author" content="Weslley Assunção (weslley@wcre8tive.com)">
   <meta name="Classification" content="accounting">
   <meta name="Description" content="A forward-thinking firm of chartered accountants for business and personal tax clients who expect the highest level of service.">
   <meta name="KeyWords" content="accountant london, accountants london, auditors london, accounting service london, london auditors,  bookkeeping services,  business startup guide, chartered accountants london, corporate tax services, financial outsourcing, financial planning services, london accountant, london accountants, management accounts, online accounting, self assessment, accountancy, accountancy services, audit, payroll, bookkeeping, VAT, finance management, management information, taxation, income tax, corporate tax, inheritance protection, asset protection, tax planning, company formation, offshore company, company incorporation, trust formation, offshore trust, accountancy software, software training, vertice services">
   <title>Vertice Services Accounting Solutions London UK. Accountants, Tax Advice, Limited Companies and Free Banking Solutions in London UK</title>
<!--
 |**************************************************************************|
 |             Vertice Services | Accounting Solutions London UK            |
 |                    Copyright 2008 © Vertice Services Ltd                 |
 |      Developed by Weslley Assunção (weslley@wcre8tive.com)              |
 |                            All rights reserved                           |
 |                                                                          |
 |             W W W . V E R T I C E S E R V I C E S . C O M                |
 |                                                                          |
 |     Web site...:  http://archived.wcre8tive.com/verticeservices          |
 |     Email......:  info@verticeservices.com                               |
 |     Webmaster..:  Weslley Assunção (weslley@wcre8tive.com)             |
 |                                                                          |
 |**************************************************************************|
  -->
<link rel="icon" href="favicon.gif" type="image/gif">
<style type="text/css">
<!--
a{text-decoration:none}
a:link { color: 3C4185; }
a:visited { color: 3C4185; }
a:active { color: 3C4185; }
a:hover { color: 3C4185; text-decoration: underline}
-->
</style>
<style type="text/css">
<!--
B{text-decoration:none}
a.B:link { color: FFFFFF; }
a.B:visited { color: FFFFFF; }
a.B::active { color: FFFFFF; }
a.B:hover { color: D6F7F7; text-decoration: underline}
-->
</style>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<style type="text/css">
<!--
BODY {
scrollbar-face-color:#C0C0C0;
scrollbar-highlight-color:#C0C0C0;
scrollbar-3dlight-color:#C0C0C0;
scrollbar-darkshadow-color:#000000;
scrollbar-shadow-color:#808080;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#E0E0E0;
}
-->
</style>
<!--End Cool Web Scrollbars code-->
<script language="JavaScript">
<!-- hide

// *********************************************************
// Script generate by Weslley Assuncao (weslley@wespadigital.com) 
// WESPA DIGITAL
// http://www.wespadigital.co.uk
// You can use this code if you leave this message
// *********************************************************

  // ok, we have a JavaScript browser
  var browserOK = false;
  var pics;

// -->
</script>
<script language="JavaScript1.1">
<!-- hide

  // JavaScript 1.1 browser - oh yes!
  browserOK = true;
  pics = new Array();

// -->
</script>
<script language="javascript">
function mail()
{
mail_str="mailto:?subject=A very interesting page"
mail_str= mail_str + "&body=Hi, I found this site Vertice Services Accounting Solutions in London UK (http://www.verticeservices.com), take a look and send me comments! " 
mail_str=mail_str + "Visit this address and tell me what you think: " + location.href 
location.href=mail_str
}
</script>
<script type="text/javascript" src="suggestMessages.js"></script>
</head>
<body>
<a NAME="index"></a>
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="780" >
<tr>
<td>
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=2 WIDTH="780" HEIGHT="47" >
<tr ALIGN=LEFT VALIGN=TOP>
<td WIDTH="19" BACKGROUND="bg_left.gif"><img SRC="top_left.gif" height=47 width=19></td>

<td WIDTH="761" BACKGROUND="bg_left.gif">
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="100%" >
<tr>
<td>
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=4 WIDTH="761" >
<tr>
<td WIDTH="20" HEIGHT="47"><img SRC="ico_clock.gif" height=15 width=15></td>

<td WIDTH="471"><b><font face="Times New Roman,Times"><font color="#000000">London,&nbsp;</font></font></b><script>
// Courtesy of SimplytheBest.net - http://simplythebest.net/scripts/
var mydate=new Date()
var theYear=mydate.getFullYear()
var day=mydate.getDay()
var month=mydate.getMonth()
var daym=mydate.getDate()
if (daym<10)
daym="0"+daym
var dayarray=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday")
var montharray=new Array("January","February","March","April","May","June","July","August","September","October","November","December")
document.write(dayarray[day]+", "+daym+" "+montharray[month]+" "+theYear)
</script>
</td>

<td WIDTH="130">
<center><!-- BEGIN Help Center Live Code, © Michael Bird 2004 --></center>

<div id="HCLInitiate" style="position:absolute; z-index:1; top: 40%; left:40%; visibility: hidden;"><a href="javascript:initiate_accept()"><img SRC="initiate.gif" BORDER=0 ></a>
<br><a href="javascript:initiate_decline()"><img SRC="initiate_close.gif" BORDER=0 ></a></div>
<script type="text/javascript" language="javascript" src="//www.archived.wcre8tive.com/verticeservices/helpdesk/lh/live.php?department=Sales"></script>
<!-- END Help Center Live Code, © Michael Bird 2004 --></td>

<td WIDTH="140">
<center><font face="Arial,Helvetica"><font size=-2>Choose your language</font></font></center>

<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=4 WIDTH="120" >
<tr>
<td HEIGHT="3"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td>
<center><img SRC="en.gif" ALT="English - UK" height=11 width=16></center>
</td>

<td>
<center><a href="http://www.archived.wcre8tive.com/verticeservices/br"><img SRC="br.gif" ALT="Português - Brasil" BORDER=0 height=11 width=16></a></center>
</td>

<td>
<center><a href="http://www.archived.wcre8tive.com/verticeservices/pl"><img SRC="pl.gif" ALT="Polski - Polska" BORDER=0 height=11 width=16></a></center>
</td>

<td>
<center><a href="http://www.archived.wcre8tive.com/verticeservices/es"><img SRC="es.gif" ALT="Castellano - España" BORDER=0 height=11 width=16></a></center>
</td>
</tr>
</table></center>
</td>
</tr>
</table>
</td>
</tr>
</table></center>
</td>
</tr>
</table>

<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="780" HEIGHT="31" >
<tr>
<td HEIGHT="31" BACKGROUND="fnd_menu_alto.gif">
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=11 WIDTH="100%" >
<tr>
<td WIDTH="100" HEIGHT="90%">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="index.htm" class="B">HOME</a></font></font></font></b></center>
</td>

<td WIDTH="2">
<center><img SRC="div_menu_top.gif" height=31 width=2></center>
</td>

<td WIDTH="120">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="about.htm" class="B">ABOUT
US</a></font></font></font></b></center>
</td>

<td WIDTH="2">
<center><img SRC="div_menu_top.gif" height=31 width=2></center>
</td>

<td WIDTH="120">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="services.htm" class="B">SERVICES</a></font></font></font></b></center>
</td>

<td WIDTH="2">
<center><img SRC="div_menu_top.gif" height=31 width=2></center>
</td>

<td WIDTH="130">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="consultacy.htm" class="B">QUESTIONS?</a></font></font></font></b></center>
</td>

<td WIDTH="2">
<center><img SRC="div_menu_top.gif" height=31 width=2></center>
</td>

<td WIDTH="140" BACKGROUND="fnd_menu_alto_in.gif">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="applyonline.htm" class="B">APPLY
ONLINE</a></font></font></font></b></center>
</td>

<td WIDTH="2">
<center><img SRC="div_menu_top.gif" height=31 width=2></center>
</td>

<td WIDTH="120">
<center><b><font face="Tahoma"><font color="#FFFFFF"><font size=-1><a href="contactus.htm" class="B">CONTACT
US</a></font></font></font></b></center>
</td>
</tr>
</table></center>
</td>
</tr>
</table></center>
</td>
</tr>

<tr>
<td><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,42,0"
  id="flash_welcome" width="780" height="113"><param name="movie" value="flash_applyonline.swf"><param name="bgcolor" value="#000063"><param name="quality" value="high"><param name="allowscriptaccess" value="samedomain"><embed type="application/x-shockwave-flash"
   pluginspage="http://www.macromedia.com/go/getflashplayer"
   width="780" height="113"
   name="flash_welcome" src="flash_applyonline.swf"
   bgcolor="#000063" quality="high"
   swLiveConnect="true" allowScriptAccess="samedomain"
  ></embed></object></td>
</tr>

<tr>
<td HEIGHT="5"></td>
</tr>

<tr>
<td>
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=2 WIDTH="760" >
<tr>
<td><font face="Verdana"><font size=-2><a href="index.htm">www.verticeservices.com</a>
> <a href="applyonline.htm">Apply Online</a> > <b>Upload Files</b></font></font></td>

<td>
<div align=right><font face="Verdana"><font size=-2>Questions? <b>Call
020 7624 1616</b> or <u><a href="contactus.htm">Email</a></u></font></font></div>
</td>
</tr>
</table></center>
</td>
</tr>

<tr>
<td HEIGHT="10"></td>
</tr>

<tr>
<td>
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=2 WIDTH="780" >
<tr ALIGN=LEFT VALIGN=TOP>
<td WIDTH="225">
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=4 WIDTH="215" >
<tr>
<td WIDTH="35"><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td WIDTH="5" BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td WIDTH="155" BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_self-employed.htm" class="B" target="_blank">Self-employed</a></font></font></font></b></td>

<td WIDTH="20"><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_limitedcompany.htm" class="B" target="_blank">Limited
Company</a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_businessbankaccount.htm" class="B" target="_blank">Business
Bank Account</a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_trademark.php" class="B" target="_blank">Trademark</a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td HEIGHT="22"><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_vsbusinessinfo.htm" class="B" target="_blank">VS
Business Information</a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_onlineseminar.htm" class="B" target="_blank">Consultation On line </a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="1"></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td><img SRC="bt_sub_left.gif" height=22 width=35></td>

<td BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" BORDER=0 height=5 width=5></td>

<td BACKGROUND="fnd_bt_sub.gif"><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_uploadfiles.php" class="B" target="_blank">Upload
Files</a></font></font></font></b></td>

<td><img SRC="bt_sub_right.gif" height=22 width=20></td>
</tr>

<tr>
<td HEIGHT="20"></td>

<td></td>

<td></td>

<td></td>
</tr>
</table>

<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="100%" >
<tr>
<td></td>
</tr>

<tr>
<td HEIGHT="10"></td>
</tr>

<tr>
<td HEIGHT="140"></td>
</tr>

<tr>
<td>
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=3 WIDTH="188" >
<tr ALIGN=LEFT VALIGN=TOP>
<td WIDTH="80"><img SRC="mascote_part01.gif" height=72 width=80></td>

<td WIDTH="95">
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="100%" >
<tr>
<td><img SRC="mascote_part02.gif" height=10 width=95></td>
</tr>

<tr ALIGN=LEFT VALIGN=TOP>
<td HEIGHT="45" BACKGROUND="mascote_part04.gif">
<center><font size=-2><font face="Arial,Helvetica">Hi, I'm </font><b><font face="Verdana">Vertice
Wizard</font></b><font face="Arial,Helvetica">, your form interactive assistant.</font></font></center>
</td>
</tr>

<tr>
<td><img SRC="mascote_part06.gif" height=17 width=95></td>
</tr>
</table>
</td>

<td WIDTH="13"><img SRC="mascote_part05.gif" height=72 width=13></td>
</tr>
</table></center>
</td>
</tr>

<tr>
<td HEIGHT="10"></td>
</tr>

<tr>
<td>
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="190" >
<tr>
<td><font face="Arial,Helvetica"><font color="#000099"><font size=-1><b>Vertice
Wizard</b> is a virtual character created to help and assist you in how
to fill in the forms. Just follow his suggestions that will appear next to the fields.</font></font></font></td>
</tr>
</table></center>
</td>
</tr>
</table>
</td>
<form action="applyonline_uploadfiles.php" method="post" enctype="multipart/form-data" name="form1" onSubmit="return (verifica())">
<td WIDTH="555"><font face="Arial,Helvetica"><font color="#428CBD"><font size=+1>Upload
Files</font></font></font>
<br><img SRC="transp.gif" height=5 width=5>
<br><img SRC="vertice_foto25.jpg" height=193 width=200 align=LEFT><font face="Arial,Helvetica"><font size=-1><b>Vertice
Services</b> requires a copy of certain documents for verification purposes
or open accounts.</font></font>
<p><font face="Arial,Helvetica"><font size=-1>Please make sure that the
documentation you provide is valid and legible. The name and address on
your documentation must correspond with the information registered on your
<b>Vertice
Services</b>&nbsp; account.&nbsp;</font></font>
<p><font face="Arial,Helvetica"><font size=-1>Your documentation cannot
be older than 6 months. Send only documents received by mail (online statements
cannot be accepted). Send all the information and documents required as
soon as possible to complete the review process.</font></font>
<p><font face="Arial,Helvetica"><font size=-1><b>Note:</b> You can upload image files with extensions <b>.gif</b>, <b>.jpg</b>, <b>.jpeg</b> or document files with extensions <b>.doc</b>, <b>.xls</b>, <b>.pdf</b>, <b>.zip</b> and <b>.rar</b>. Send up to 3MB by file.</font></font>
<br><p><font face="Verdana"><font size=-2>Items indicated with an arrow (<img SRC="arrow-right_red.gif" height=15 width=15>)
are mandatory.</font></font>



<br>            <input value="File received from Vertice Services website" name="about" type="hidden">
     <?
	 if(!$send){
	 ?>

<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="540" >
<tr>
<td WIDTH="110" BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="15" BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="5" BACKGROUND="fnd_bt_sub.gif"><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="180" HEIGHT="25" BACKGROUND="fnd_bt_sub.gif"><b><font face="Arial,Helvetica"><font color="#FFFFFF"><font size=-1>Attach
a file</font></font></font></b><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="5"></td>

<td WIDTH="230"></td>
</tr>

<tr>
<td></td>

<td></td>

<td></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td HEIGHT="35">
<div align=right><b><font face="Verdana"><font color="#000000"><font size=-2>Your
Name</font></font></font></b></div>
</td>

<td><img SRC="arrow-right_red.gif" height=15 width=15></td>

<td></td>

<td><input name="name" size="57" style="width:180px;height:20px;font-size:8pt;text-align:left;padding-left:5px;font-family:Verdana;font-weight:italic;color:404040;border-style:solid;border-width:1px;border-color:404040;background-image:url(fnd-form.gif);"></td>

<td></td>

<td></td>
</tr>

<tr>
<td HEIGHT="35">
<div align=right><b><font face="Verdana"><font color="#000000"><font size=-2>Your
Email</font></font></font></b></div>
</td>

<td><img SRC="arrow-right_red.gif" height=15 width=15></td>

<td></td>

<td><input name="email" size="57" style="width:180px;height:20px;font-size:8pt;text-align:left;padding-left:5px;font-family:Verdana;font-weight:italic;color:404040;border-style:solid;border-width:1px;border-color:404040;background-image:url(fnd-form.gif);"></td>

<td></td>

<td></td>
</tr>

<tr ALIGN=LEFT VALIGN=CENTER>
<td HEIGHT="45">
<div align=right><b><font face="Verdana"><font color="#000000"><font size=-2>File</font></font></font></b></div>
</td>

<td><img SRC="arrow-right_red.gif" height=15 width=15></td>

<td></td>

<td><p>
              <input type="file" name="file[]" id="file[]" onFocus="javascript:toggleMsg('msg-01')" onBlur="javascript:toggleMsg('msg-01')">
              <br>
 
                </p></td>

<td></td>

<td><span id="msg-01" class="msg" style="visibility:hidden;">
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<tr>
<td><img SRC="mascote_mini01.gif" height=25 width=33></td>

<td BACKGROUND="mascote_mini02.gif"><font face="Arial,Helvetica"><font color="#CC0000"><font size=-2>.doc, .pdf, .gif, .jpg or .jpeg</font></font></font></td>

<td><img SRC="mascote_mini03.gif" height=25 width=13></td>
</tr>
</table>
</span></td>
</tr>

<tr>
<td HEIGHT="35">
<div align=right><b><font face="Verdana"><font color="#000000"><font size=-2>File
Title</font></font></font></b></div>
</td>

<td><img SRC="arrow-right_red.gif" height=15 width=15></td>

<td></td>

<td><input name="file_title" onFocus="javascript:toggleMsg('msg-02')" onBlur="javascript:toggleMsg('msg-02')"  style="width:180px;height:20px;font-size:8pt;text-align:left;padding-left:5px;font-family:Verdana;font-weight:italic;color:404040;border-style:solid;border-width:1px;border-color:404040;background-image:url(fnd-form.gif);"></td>

<td></td>

<td><span id="msg-02" class="msg" style="visibility:hidden;">
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<tr>
<td><img SRC="mascote_mini01.gif" height=25 width=33></td>

<td BACKGROUND="mascote_mini02.gif"><font face="Arial,Helvetica"><font color="#CC0000"><font size=-2>e.g.,
"first page of statement"</font></font></font></td>

<td><img SRC="mascote_mini03.gif" height=25 width=13></td>
</tr>
</table>
</span></td>
</tr>

<tr>
<td>
<div align=right><b><font face="Verdana"><font color="#000000"><font size=-2>File
Description</font></font></font></b>
<br><font face="Verdana"><font color="#000000"><font size=-2>(optional)</font></font></font></div>
</td>

<td></td>

<td></td>

<td><textarea name="file_description" onFocus="javascript:toggleMsg('msg-03')" onBlur="javascript:toggleMsg('msg-03')"  rows=5 cols=45 wrap=virtual  style="width:180px;height:80px;font-size:8pt;text-align:left;padding-left:5px;font-family:Verdana;font-weight:italic;color:303061;border-style:solid;border-width:1px;border-color:000000;background-image:url(fnd-form.gif);"></textarea></td>

<td></td>

<td><span id="msg-03" class="msg" style="visibility:hidden;">
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<tr>
<td><img SRC="mascote_mini01.gif" height=25 width=33></td>

<td BACKGROUND="mascote_mini02.gif"><font face="Arial,Helvetica"><font color="#CC0000"><font size=-2>comments about the file</font></font></font></td>

<td><img SRC="mascote_mini03.gif" height=25 width=13></td>
</tr>
</table>
</span></td>
</tr>

<tr>
<td HEIGHT="20"></td>

<td></td>

<td></td>

<td></td>

<td></td>

<td></td>
</tr>

<tr>
<td></td>

<td></td>

<td></td>

<td>

<center>
<input type="image" name="boton" src="bt-send.gif" width="55" height="25" hspace0"1" align="middle"></center>
</form></td>

      <? }else{?><br><br>
      <center><table BORDER=0 CELLSPACING=0 CELLPADDING=4 COLS=1 WIDTH="300" >
<tr>
<td BGCOLOR="#FED149"><b><font face="Arial,Helvetica">Thank you!</font></b><font face="Arial,Helvetica"><font size=-1></font></font>
<p><font face="Arial,Helvetica"><font size=-1>Your document has been received
at <b>Vertice Services</b>. If you need to send more documents, just <b><a href="http://www.archived.wcre8tive.com/verticeservices/applyonline_uploadfiles.php">click
here</a></b>.</font></font></td>
</tr>
</table></center><br><br>
      
      <? }?>
<td></td>

<td></td>
</tr>
</table></center>
</td>
</tr>

<tr>
<td HEIGHT="20"></td>

<td></td>
</tr>
</table>
</td>
</tr>

<tr>
<td></td>
</tr>

<tr>
<td HEIGHT="25" BACKGROUND="fnd_blue_footer.gif">
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<tr>
<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="index.htm" class="B">home</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="about.htm" class="B">about
us</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="services.htm" class="B">services</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="consultacy.htm" class="B">questions</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="applyonline.htm" class="B">apply
online</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="contactus.htm" class="B">contact
us</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td><b><font face="Verdana"><font color="#FFFFFF"><font size=-2><a href="consultancy_usefullinks.htm" class="B">useful
links</a></font></font></font></b></td>

<td WIDTH="20">
<center><img SRC="div_blue_footer.gif" height=25 width=10></center>
</td>

<td WIDTH="30">
<center><img SRC="en.gif" ALT="English - UK" height=11 width=16></center>
</td>

<td WIDTH="30">
<center><a href="http://www.archived.wcre8tive.com/verticeservices/br"><img SRC="br.gif" ALT="Português - Brasil" BORDER=0 height=11 width=16></a></center>
</td>

<td WIDTH="30">
<center><a href="http://www.archived.wcre8tive.com/verticeservices/pl"><img SRC="pl.gif" ALT="Polski - Polska" BORDER=0 height=11 width=16></a></center>
</td>

<td WIDTH="30">
<center><a href="http://www.archived.wcre8tive.com/verticeservices/es"><img SRC="es.gif" ALT="Castellano - España" BORDER=0 height=11 width=16></a></center>
</td>
</tr>
</table></center>
</td>
</tr>

<tr>
<td HEIGHT="20">
<div align=right><img SRC="payment_right.gif" height=33 width=506></div>
</td>
</tr>

<tr>
<td>
<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="100%" >
<tr>
<td HEIGHT="10"></td>
</tr>

<tr>
<td HEIGHT="50">&nbsp;</td>
</tr>
</table>

<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="780" >
<tr>
<td WIDTH="115">
<center><font face="Arial,Helvetica"><font color="#666666"><font size=-2>web
developed by</font></font></font>
<br><a href="http://www.wespadigital.co.uk" target="new"><img SRC="lg-wi.gif" ALT="WESPA Digital" BORDER=0 height=36 width=114></a></center>
</td>

<td WIDTH="550">
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=1 WIDTH="100%" >
<tr>
<td>
<center><font color="#000000"><font size=-2><font face="Arial, Helvetica, sans-serif">Copyright
2008 </font><b><font face="Verdana, Arial">Vertice Services Ltd</font></b></font></font></center>
</td>
</tr>

<tr>
<td>
<center><font color="#000000"><font size=-2><font face="Arial, Helvetica, sans-serif">All
rights reserved. </font><font face="Arial,Helvetica">Webmaster
<a href="mailto:weslley@wcre8tive.com">Weslley Assunção</a></font></font></font></center>
</td>
</tr>

<tr>
<td>
<center><font color="#000000"><font size=-2><font face="Arial,Helvetica">63
Loveridge Rd. NW6 2DR London Tel: </font><b><font face="Verdana">020 7624
1616</font></b><font face="Arial,Helvetica">&nbsp;&nbsp; Fax:
</font><b><font face="Verdana">020
7624 2121</font></b></font></font></center>
</td>
</tr>

<tr>
<td>
<center><font color="#000000"><font size=-2><font face="Arial,Helvetica">email:
</font><b><font face="Verdana"><a href="mailto:info@verticeservices.com">info@verticeservices.com</a></font></b></font></font></center>
</td>
</tr>
</table></center>
</td>

<td WIDTH="115">
<center><a href="http://www.macromedia.com/go/flashplayer" target="new"><img SRC="getflash.gif" ALT="Download FREE Macromedia Flash" BORDER=0 height=31 width=88></a></center>
</td>
</tr>
</table></center>
<img SRC="transp.gif" height=5 width=5></td>
</tr>

<tr>
<td HEIGHT="20"></td>
</tr>

<tr>
<td>
<center><table BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="370" >
<tr ALIGN=LEFT VALIGN=CENTER>
<td WIDTH="13"><a href="#index"><img SRC="ico_top.gif" ALT="Go to top page" BORDER=0 height=13 width=13 align=TEXTTOP></a></td>

<td WIDTH="5"><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="90"><font face="Arial,Helvetica"><font size=-2><a href="#index">go
to top</a></font></font></td>

<td><a href="#top"><img SRC="ico_mail.gif" ALT="Send this page to a friend" BORDER=0 height=13 width=13 align=TEXTTOP></a></td>

<td WIDTH="5"><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="110"><font face="Arial,Helvetica"><font size=-2><a href="javascript:mail()">send
to a friend</a></font></font></td>

<td><a href="#print" onclick="self.print()"><img SRC="ico_print.gif" ALT="Print this page" BORDER=0 height=13 width=13 align=TEXTTOP></a></td>

<td><img SRC="transp.gif" height=5 width=5></td>

<td WIDTH="109"><font face="Arial,Helvetica"><font size=-2><a href="#print" onclick="self.print()">print
this page</a></font></font></td>
</tr>
</table></center>
</td>
</tr>
</table></center>

<br><br>
</body>
</html>

